#!/bin/bash
# Recibe 2 parametros

if [$# -ne 2] 
then
	echo "CANTIDAD DE PARAMETROS RECIBIDOS INCORRECTA"
else
#	echo "Introduzca los dos digitos: "
#	read num1 num2
	echo "Suma: $(expr $1 + $2)"
	echo "Resta: $(expr $1 - $2)"
	echo "Multiplicacion: $(expr $1  \* $2)"
	echo "Division: $(expr $1 / $2)"
	if [$1 -gt $2] 
	then
		echo "El mayor es $1"
	else
		echo "El mayor es $2"
	fi
fi
