#!/bin/bash
# Recibe 2 parametros

if [ $# -ne 2 ] 
then
  echo "CANTIDAD DE PARAMETROS RECIBIDOS INCORRECTA"
else
  echo "Suma: $(expr $1 + $2)"
  echo "Resta: $(expr $1 - $2)"
  echo "Multiplicacion: $(expr $1  \* $2)"
  echo "Division: $(expr $1 / $2)"
  if [ $! -gt $2 ] 
  then
    echo "El mayor es $1"
  else
    echo "El mayor es $2"
  fi
fi
