#!/bin/bash
# Recibe 3 parametros, path, opcion y cadena

if [ $# -ne 3 ]
then
	echo "CANTIDAD DE PARAMETROS RECIBIDOS INCORRECTA"
	exit 1
else
	case $2 in
		"-a")
			for FILE in $(ls $1)
			do
			mv $1/$FILE $1/$FILE$3
			done
			;;
		"-b")
			for FILE in $(ls $1)
			do
				mv $1/$FILE $1/$3$FILE
			done
			;;
	esac
fi
exit 0

