#!/bin/bash
#Recibe un usuario como parametro

if [ $# -ne 1 ]
then
	echo "CANTIDAD DE PARAMETROS RECIBIDOS INCORRECTA"
	exit 2
fi

existe=$(cat /etc/passwd | grep $1 | wc -l)
if [ $existe == 0 ]
then
	echo "Usuario inexistente"
	exit 1
fi
cant=0
while true
do
	usuario=$(users | grep $1 | wc -l)
	if [ $usuario -eq 1 ]
	then
		let cant++
		echo "$1 $(date)" >> /usr/access-"$1".log
	fi
	if [ $cant -eq 30 ]
	then
		exit 0
	fi
	sleep 30
done

