#!/bin/bash
# No recibe parametros

if [ $# -ne 0 ]
then
	echo CANTIDAD DE PARAMETROS RECIBIDOS INCORRECTA
	exit 0
fi

num=(10 3 5 7 9 3 5 4)

productoria(){
	total=1
	for ((i=0; i<${#num[@]}; i++))
	do
		total=`expr $total \* ${num[$i]}`
	done
}

productoria
echo "Resultado: $total"
