#!/bin/bash
# No recibe parametros

if [ $# -ne 0 ]
then
	echo CANTIDAD DE PARAMETROS RECIIBDOS INCORRECTA
	exit 1
fi

arreglo=(1 2 3 4 5 6)
cant=0
for ((i=0; i<${#arreglo[@]}; i++))
do
	n=`expr ${arreglo[$i]} % 2`
	if [ $n -eq 0]
	then
		echo ${arreglo[$i]}
	else
		let cant++
	fi
done
echo "Cantidad de impares = $cant"
exit 0
